abstract class InspectAllProductsState{}
class InspectAllProductsInitialState extends InspectAllProductsState{}
class InspectAllProductsClearState extends InspectAllProductsState{}
class InspectAllProductsChangedState extends InspectAllProductsState{}